export const INITCRUMB = 'INITCRUMB'

export const UPDATAACCOUNT = 'UPDATAACCOUNT'

export const UPDATAPASS = 'UPDATAPASS'

export const LOGINRESET = 'LOGINRESET'

export const UPDATALOGINSTATUS = 'UPDATALOGINSTATUS'

export const CRUMBCHANGE = 'CRUMBCHANGE'

export const SMALLIMAGECHANGE = 'SMALLIMAGECHANGE'

export const LARGEIMAGECHANGE = 'LARGEIMAGECHANGE'

export const UPDATECOUNTRY = 'UPDATECOUNTRY'

export const UPDATEAREA = 'UPDATEAREA'

export const UPDATEINTROS = 'UPDATEINTROS'

export const UPDATENAME = 'UPDATENAME'

export const UPDATEENNAME = 'UPDATEENNAME'

export const UPDATETYPE = 'UPDATETYPE'

export const UPDATESMALLIMAGE = 'UPDATESMALLIMAGE'

export const UPDATELARGERIMAGE = 'UPDATELARGERIMAGE'

export const UPDATELISTIMAGE = 'UPDATELISTIMAGE'

export const EMPTYFORM = 'EMPTYFORM'

export const EDITFORM = 'EDITFORM'

export const EDITACITVEFORM = 'EDITACITVEFORM'

export const UPDATEBANNERIMAGE = 'UPDATEBANNERIMAGE'

export const EMPTYBANNER = 'EMPTYBANNER'

export const UPDATEACTIVELISTIMAGE = 'UPDATEACTIVELISTIMAGE'

export const UPDATEACTIVEDTAILIMAGE = 'UPDATEACTIVEDTAILIMAGE'

export const UPDATEACTIVETITLEFIRST = 'UPDATEACTIVETITLEFIRST'

export const UPDATEACTIVETITLESECOND = 'UPDATEACTIVETITLESECOND'

export const EMPTYACTIVE = 'EMPTYACTIVE'

export const UPDATERECRUITMENTNAME = 'UPDATERECRUITMENTNAME'

export const UPDATERECRUITMENTZHIZE = 'UPDATERECRUITMENTZHIZE'

export const UPDATERECRUITMENTZIGE = 'UPDATERECRUITMENTZIGE'

export const EMPTYRECRUITMENT = 'EMPTYRECRUITMENT'
